/* 도구 레지스트리 — 단일 진실원 (single source of truth).
   index.html 의 허브가 이 배열을 렌더한다. 새 도구 추가 = 여기 1줄 + 해당 html + i18n.js 의 tool.{key}.t/.d.
   필드: key(고유), h(href), ic(아이콘), chip(아이콘 배경색 c-*), cat(카테고리), k(검색 키워드 다국어).
   제목·설명은 i18n.js 의 tool.{key}.t / tool.{key}.d 에서 가져온다 (4개국어). */
window.TOOLS = [
  { key:'char',  h:'char-counter.html', ic:'✍️', chip:'c-blue',   cat:'텍스트', k:'글자수 character counter 원고지 단어 word count 자소서 字数 文字数', related:['text','diff','lorem'] },
  { key:'date',  h:'date-calc.html',    ic:'📅', chip:'c-green',  cat:'계산기', k:'만나이 나이 dday 디데이 날짜 date age 年龄 倒数 年齢', related:['lunar','worldclock','timer'] },
  { key:'qr',    h:'qr.html',           ic:'🔳', chip:'c-violet', cat:'생성기', k:'qr 큐알 二维码 url 와이파이', related:['pw','uuid','lotto'] },
  { key:'pw',    h:'password.html',     ic:'🔑', chip:'c-rose',   cat:'생성기', k:'비밀번호 password 密码 パスワード 랜덤 보안', related:['uuid','crypt','qr'] },
  { key:'unit',  h:'unit.html',         ic:'📐', chip:'c-amber',  cat:'변환기', k:'단위 변환 unit 单位 単位 길이 무게 온도 평', related:['pyeong','color','base64'] },
  { key:'color', h:'color.html',        ic:'🎨', chip:'c-cyan',   cat:'변환기', k:'색상 color 颜色 カラー hex rgb hsl', related:['contrast','diagram','favicon'] },
  { key:'image', h:'image.html',        ic:'🖼️', chip:'c-green',  cat:'이미지', k:'이미지 압축 리사이즈 image 图片 画像 png jpg webp', related:['imgcrop','exif','favicon'] },
  { key:'text',  h:'text-tools.html',   ic:'🧹', chip:'c-blue',   cat:'텍스트', k:'텍스트 정리 text 文本 テキスト 대소문자 중복 정렬', related:['char','diff','lorem'] },
  { key:'base64',h:'base64.html',       ic:'🔤', chip:'c-cyan',   cat:'변환기', k:'base64 인코딩 디코딩 encode decode 编解码 エンコード', related:['json','urlencode','hash'] },
  { key:'lotto', h:'lotto.html',        ic:'🎲', chip:'c-rose',   cat:'생성기', k:'로또 lotto 번호 추첨 645 乐透 ロト random', related:['ladder','pw','uuid'] },
  { key:'pmerge',   h:'merge.html',       ic:'📎', chip:'c-rose',   cat:'PDF', k:'pdf 합치기 병합 merge combine 合并 結合 묶기', related:['psplit','img2pdf','pcompress'] },
  { key:'psplit',   h:'split.html',       ic:'✂️', chip:'c-amber',  cat:'PDF', k:'pdf 쪼개기 분할 추출 split extract 拆分 分割 페이지', related:['pmerge','img2pdf'] },
  { key:'img2pdf',  h:'img2pdf.html',     ic:'🖼️', chip:'c-green',  cat:'PDF', k:'이미지 pdf 변환 image to pdf jpg png 图片 画像', related:['pmerge','image','imgcrop'] },
  { key:'pcompress',h:'pdf-compress.html',ic:'📦', chip:'c-blue',   cat:'PDF', k:'pdf 압축 용량 compress 压缩 圧縮 줄이기 reduce' },
  { key:'json',  h:'json.html',     ic:'🧩', chip:'c-amber',  cat:'개발자', k:'json 포맷 검증 formatter validator beautify minify 格式化 整形 파싱 lint', related:['jsoncsv','regex','base64'] },
  { key:'regex', h:'regex.html',    ic:'🔎', chip:'c-violet', cat:'개발자', k:'정규식 정규표현식 regex regexp 正则 正規表現 패턴 pattern 테스트', related:['json','diff','text'] },
  { key:'md',    h:'markdown.html', ic:'📝', chip:'c-blue',   cat:'개발자', k:'마크다운 markdown 에디터 editor preview md 编辑 プレビュー 온라인', related:['json','diff','text'] },
  { key:'favicon',h:'favicon.html', ic:'⭐', chip:'c-amber',  cat:'이미지', k:'파비콘 favicon 즐겨찾기 아이콘 icon ico 图标 アイコン 생성', related:['diagram','imgcrop','color'] },
  { key:'diagram',h:'diagram.html', ic:'🔷', chip:'c-violet', cat:'이미지', k:'다이어그램 diagram svg 도식 순서도 flowchart 图示 図解 박스 화살표', related:['favicon','color','qr'] },
  { key:'lunar',  h:'lunar.html',     ic:'🌙', chip:'c-amber',  cat:'변환기', k:'음력 양력 변환 lunar solar 农历 旧暦 설날 추석 간지 띠 윤달 calendar', related:['date','worldclock'] },
  { key:'worldclock',h:'worldclock.html',ic:'🌏', chip:'c-cyan', cat:'시간', k:'세계 시계 시간 timezone world clock 时区 时差 タイムゾーン 회의 utc gmt', related:['timer','date','lunar'] },
  { key:'mask',  h:'pii.html',        ic:'🛡️', chip:'c-rose',  cat:'개인정보', k:'개인정보 탐지 마스킹 비식별 가명 masking pii privacy 주민번호 사업자번호 전화 이메일 카드 ip 계좌 체크섬 luhn 个人信息 脱敏 個人情報', related:['pseudo','reid','exif'] },
  { key:'reid',  h:'reid.html',       ic:'🔐', chip:'c-violet', cat:'개인정보', k:'재식별 위험 평가 k익명성 l다양성 t근접성 k-anonymity l-diversity t-closeness 비식별 가명정보 익명처리 re-identification 准标识符 匿名化 匿名加工', related:['profiler','geodeid','pseudo'] },
  { key:'gmap',  h:'map.html',        ic:'🗺️', chip:'c-green', cat:'GIS', k:'gis 지도 웹맵 map 거리 면적 측정 버퍼 히트맵 클러스터 osm vworld 地图 空间 좌표', related:['csvmap','coord','geom'] },
  { key:'coord', h:'coord.html',      ic:'🧭', chip:'c-cyan',  cat:'GIS', k:'좌표 변환 좌표계 경위도 위경도 utm-k 중부원점 tm epsg 도분초 dms proj4 coordinate 坐标 座標', related:['csvmap','geom','geoconv'] },
  { key:'geom',  h:'geometry.html',   ic:'🔺', chip:'c-violet', cat:'GIS', k:'wkt wkb ewkb geojson 변환 지오메트리 geometry postgis hex 면적 거리 정점 polygon 转换 几何 ジオメトリ', related:['coord','geoops','geoconv'] },
  { key:'csvmap',h:'csvmap.html',     ic:'📍', chip:'c-amber', cat:'GIS', k:'csv 지도 마커 좌표 위경도 위도 경도 geojson 시각화 점 데이터 utm-k 중부원점 proj4 map marker 坐标 地图 マップ', related:['coord','geoconv','profiler'] },
  { key:'geoconv',h:'geoconvert.html', ic:'🔄', chip:'c-blue', cat:'GIS', k:'shapefile shp kml gpx geojson 변환 conversion 지오메트리 좌표 gps 구글어스 google earth prj zip 转换 変換', related:['geom','coord','csvmap'] },
  { key:'geodeid',h:'geodeid.html',    ic:'🔏', chip:'c-rose', cat:'GIS', k:'위치 비식별 익명화 마스킹 지오마스킹 격자 스냅 라운딩 k익명성 k-anonymity geomasking grid privacy 개인정보 가명 좌표 익명 脱敏 匿名 マスキング', related:['reid','geoops','pseudo'] },
  { key:'geoops', h:'geoops.html',     ic:'🔧', chip:'c-green', cat:'GIS', k:'공간 연산 버퍼 buffer 단순화 simplify 컨벡스 헐 convex hull 중심점 centroid 바운딩 박스 bbox 도형 geometry turf 面积 缓冲 简化 凸包 バッファ', related:['geom','geodeid','coord'] },
  { key:'korpoint',h:'korpoint.html',  ic:'📌', chip:'c-cyan', cat:'GIS', k:'국가지점번호 격자 위치표시번호 좌표 변환 행정안전부 가나다 utm-k national point number 산악 해안 grid 国家地点编号 座標', related:['coord','geom','csvmap'] },
  { key:'legaldong',h:'legaldong.html', ic:'📜', chip:'c-amber', cat:'GIS', k:'법정동 코드 법정동코드 행정동 시도 시군구 읍면동 리 주소 코드 검색 국토교통부 legal dong code address 법정 동 行政区划 法定洞 코드검색', related:['coord','csvmap'] },
  { key:'salary', h:'salary.html',   ic:'💰', chip:'c-green',  cat:'계산기', k:'연봉 실수령액 월급 세후 실수령 급여 4대보험 국민연금 건강보험 소득세 salary net pay take home 月薪 手取り 税後 연봉계산기', related:['loan','vat','pyeong'] },
  { key:'pyeong', h:'pyeong.html',   ic:'📐', chip:'c-amber',  cat:'계산기', k:'평수 평 제곱미터 면적 변환 평형 아파트 부동산 토지 헥타르 sqm pyeong area 坪 平米 面積 평수계산기', related:['unit','salary','percent'] },
  { key:'exif',   h:'exif.html',     ic:'📷', chip:'c-rose',   cat:'개인정보', k:'exif 위치정보 gps 메타데이터 사진 이미지 제거 privacy metadata 个人信息 메타 데이터 写真 メタデータ 사진위치', related:['imgcrop','mask','pseudo'] },
  { key:'hash',   h:'hash.html',     ic:'#️⃣', chip:'c-violet', cat:'개발자', k:'md5 sha256 sha1 sha512 해시 hash 체크섬 checksum 무결성 verify 哈希 ハッシュ 해시생성', related:['crypt','pseudo','uuid'] },
  { key:'uuid',   h:'uuid.html',     ic:'🆔', chip:'c-cyan',   cat:'개발자', k:'uuid guid 고유 식별자 생성 unique id generator 唯一标识 識別子 유유아이디', related:['hash','pw','timestamp'] },
  { key:'ladder', h:'ladder.html',   ic:'🪜', chip:'c-rose',   cat:'생성기', k:'사다리타기 사다리 추첨 제비뽑기 뽑기 내기 ladder game 抽签 くじ あみだくじ 사다리게임', related:['lotto','pw'] },
  { key:'loan',   h:'loan.html',     ic:'🏦', chip:'c-green',  cat:'계산기', k:'대출 이자 계산기 원리금 원금균등 만기일시 이자 상환 월납입 금리 loan interest 贷款 利息 ローン 대출계산기', related:['salary','vat','percent'] },
  { key:'percent',h:'percent.html',  ic:'％', chip:'c-violet', cat:'계산기', k:'퍼센트 계산기 백분율 비율 할인 인상 증감률 percent percentage 百分比 パーセント 퍼센트계산', related:['vat','loan','numkor'] },
  { key:'diff',   h:'diff.html',     ic:'🔀', chip:'c-blue',   cat:'개발자', k:'텍스트 비교 차이 diff 비교 변경 두 글 compare difference 文本对比 差分 텍스트비교', related:['text','json'] },
  { key:'jsoncsv',h:'jsoncsv.html',  ic:'🔄', chip:'c-amber',  cat:'개발자', k:'json csv 변환 convert 표 table 데이터 转换 변환 제이슨 csv변환', related:['csvclean','json','profiler'] },
  { key:'timestamp',h:'timestamp.html', ic:'⏱️', chip:'c-cyan', cat:'개발자', k:'timestamp unix epoch 타임스탬프 시간 변환 날짜 시각 epoch time 时间戳 タイムスタンプ 유닉스시간', related:['worldclock','date','uuid'] },
  { key:'numkor', h:'numkor.html',   ic:'🔢', chip:'c-cyan',   cat:'변환기', k:'숫자 한글 금액 변환 한글금액 일금 원정 한자 갖은자 대문자 number to korean amount 金额 数字 영수증 계약서 세금계산서 숫자한글', related:['vat','percent'] },
  { key:'bmi',    h:'bmi.html',      ic:'⚖️', chip:'c-green',  cat:'건강', k:'bmi 체질량지수 비만도 비만 과체중 저체중 표준체중 키 몸무게 신장 체중 다이어트 body mass index 肥満 体重 计算 비엠아이', related:['calorie','heartrate','percent'] },
  { key:'pseudo', h:'pseudo.html',   ic:'🎭', chip:'c-violet', cat:'개인정보', k:'가명처리 가명화 비식별 익명화 해시 솔트 salt sha256 일관 가명 id pseudonymization hashing 가명정보 개인정보 결합키 脱敏 仮名化 익명 데이터결합', related:['mask','reid','profiler'] },
  { key:'vat',     h:'vat.html',       ic:'🧾', chip:'c-green',  cat:'계산기', k:'부가세 vat 부가가치세 세금 공급가 공급가액 합계 세액 역산 10% 세율 사업자 세금계산서 영수증 税 增值税 消費税 부가세계산기', related:['salary','loan','percent'] },
  { key:'urlencode',h:'urlencode.html',ic:'🔗', chip:'c-blue',   cat:'개발자', k:'url 인코딩 디코딩 encode decode percent uri 퍼센트 쿼리 한글 escape unescape 编码 解码 エンコード url인코딩', related:['base64','jwt','json'] },
  { key:'jwt',     h:'jwt.html',       ic:'🪪', chip:'c-violet', cat:'개발자', k:'jwt json web token 디코더 decode header payload 토큰 base64url 클레임 exp iat 解析 デコード 제이슨웹토큰', related:['base64','json','hash'] },
  { key:'contrast',h:'contrast.html',  ic:'🌗', chip:'c-amber',  cat:'변환기', k:'색 대비 명도대비 contrast ratio wcag 접근성 가독성 aa aaa 색상 전경 배경 명암 对比度 コントラスト 색대비검사', related:['color','favicon'] },
  { key:'timer',  h:'timer.html',     ic:'⏲️', chip:'c-rose',   cat:'시간', k:'타이머 스톱워치 카운트다운 알람 시간 측정 랩 뽀모도로 timer stopwatch countdown 计时 タイマー 스톱워치', related:['worldclock','date'] },
  { key:'lorem',  h:'lorem.html',     ic:'📄', chip:'c-blue',   cat:'생성기', k:'로렘입숨 더미텍스트 더미 텍스트 lorem ipsum placeholder 채우기 샘플 텍스트 한글 시안 목업 假文 ダミーテキスト 더미텍스트', related:['char','text','uuid'] },
  { key:'imgcrop',h:'imgcrop.html',   ic:'✂️', chip:'c-green',  cat:'이미지', k:'이미지 자르기 크롭 crop 회전 반전 rotate flip 사진 편집 비율 썸네일 잘라내기 裁剪 トリミング 이미지자르기', related:['image','exif','favicon'] },
  { key:'crypt',  h:'crypt.html',     ic:'🔒', chip:'c-violet', cat:'개인정보', k:'암호화 복호화 텍스트 암호 비밀번호 aes aes256 gcm 보안 메모 encrypt decrypt password 加密 暗号化 텍스트암호화 메모암호', related:['hash','pseudo','mask'] },
  { key:'profiler',h:'profiler.html', ic:'🔬', chip:'c-cyan',   cat:'데이터', k:'데이터 프로파일러 eda 분석 csv 열 자료형 결측 고유값 통계 분포 준식별자 profiling data profile 데이터분석 探索 데이터프로파일', related:['reid','pseudo','csvclean'] },
  { key:'csvclean',h:'csvclean.html', ic:'🧼', chip:'c-green',  cat:'데이터', k:'csv 정제 정리 클렌징 공백 제거 중복 행 제거 빈행 헤더 정규화 구분자 변환 cleaning clean 清洗 데이터정제 csv정리', related:['profiler','jsoncsv','csvmap'] },
  { key:'gradient',h:'gradient.html', ic:'🌈', chip:'c-violet', cat:'이미지', k:'그라데이션 그라디언트 css gradient 선형 원형 배경 색상 디자인 渐变 グラデーション 그라데이션생성', related:['color','contrast','favicon'] },
  { key:'workdays',h:'workdays.html', ic:'📆', chip:'c-green',  cat:'계산기', k:'영업일 근무일 평일 주말 제외 공휴일 납기 영업일계산 business days working days 工作日 営業日 근무일수', related:['date','salary','timer'] },
  { key:'caseconv',h:'caseconv.html', ic:'🔠', chip:'c-blue',   cat:'개발자', k:'표기 변환 케이스 camelcase snakecase kebab pascalcase 대소문자 변수명 슬러그 命名 ケース 카멜케이스', related:['text','json','regex'] },
  { key:'csvtable',h:'csvtable.html', ic:'📋', chip:'c-amber',  cat:'데이터', k:'csv 표 변환 마크다운 markdown html table 깃허브 문서 블로그 表格 テーブル csv표', related:['jsoncsv','csvclean','profiler'] },
  { key:'calorie',h:'calorie.html',  ic:'🍎', chip:'c-green',  cat:'건강', k:'칼로리 기초대사량 bmr tdee 권장 섭취 다이어트 감량 증량 열량 체중 calorie 卡路里 カロリー 칼로리계산', related:['bmi','heartrate','sleep'] },
  { key:'heartrate',h:'heartrate.html', ic:'❤️', chip:'c-rose', cat:'건강', k:'심박수 목표 심박수 최대 운동 강도 카보넨 유산소 지방연소 heart rate 心率 心拍数 심박', related:['calorie','bmi','timer'] },
  { key:'sleep',  h:'sleep.html',     ic:'😴', chip:'c-violet', cat:'건강', k:'수면 시간 수면주기 취침 기상 90분 렘 꿀잠 잠 sleep cycle 睡眠 睡眠周期 수면시간', related:['heartrate','calorie','worldclock'] },
  { key:'g2048', h:'2048.html',     ic:'🔢', chip:'c-amber',  cat:'게임', k:'2048 게임 퍼즐 숫자 합치기 puzzle game 二零四八 ゲーム 이천사십팔', related:['memorygame','breakout','tictactoe'] },
  { key:'breakout',h:'breakout.html',ic:'🧱', chip:'c-rose',  cat:'게임', k:'벽돌깨기 breakout 공 막대 액션 게임 arcade 打砖块 ブロック崩し 벽돌', related:['g2048','tictactoe','memorygame'] },
  { key:'memorygame',h:'memory.html',ic:'🃏', chip:'c-violet',cat:'게임', k:'메모리 카드 맞추기 기억력 게임 짝 맞추기 memory match 记忆 神経衰弱 카드게임', related:['g2048','breakout','tictactoe'] },
  { key:'tictactoe',h:'tictactoe.html',ic:'⭕', chip:'c-blue', cat:'게임', k:'틱택토 삼목 오목 tic tac toe 컴퓨터 ai 2인 전략 게임 井字棋 三目並べ 틱택토', related:['g2048','memorygame','breakout'] },
  { key:'snake', h:'snake.html',     ic:'🐍', chip:'c-green',  cat:'게임', k:'스네이크 뱀 게임 snake 먹이 액션 arcade 贪吃蛇 スネーク 뱀게임', related:['breakout','whack','g2048'] },
  { key:'pong',  h:'pong.html',      ic:'🏓', chip:'c-cyan',   cat:'게임', k:'핑퐁 퐁 pong 탁구 막대 공 2인 ai 액션 게임 乒乓 ピンポン 핑퐁게임', related:['breakout','tictactoe','snake'] },
  { key:'minesweeper',h:'minesweeper.html',ic:'💣', chip:'c-rose', cat:'게임', k:'지뢰찾기 마인스위퍼 minesweeper 지뢰 퍼즐 게임 扫雷 マインスイーパ 지뢰게임', related:['memorygame','g2048','tictactoe'] },
  { key:'whack', h:'whack.html',     ic:'🦫', chip:'c-amber',  cat:'게임', k:'두더지 잡기 두더지잡기 whack a mole 반응속도 액션 게임 打地鼠 もぐらたたき 두더지게임', related:['snake','breakout','pong'] },
  { key:'spaceshooter',h:'spaceshooter.html',ic:'🚀', chip:'c-cyan', cat:'게임', k:'우주 슈팅 슈팅 게임 비행 슈팅 space shooter 총알 적 액션 射击 シューティング 우주게임', related:['snake','breakout','whack'] },
  { key:'cardodge',h:'cardodge.html', ic:'🏎️', chip:'c-rose', cat:'게임', k:'자동차 회피 레이싱 자동차 게임 운전 피하기 car dodge racing 赛车 躲避 レーシング 자동차게임', related:['snake','spaceshooter','whack'] },
  { key:'gomoku',h:'gomoku.html',   ic:'⚫', chip:'c-amber', cat:'게임', k:'오목 게임 오목 gomoku 五목 바둑 돌 전략 2인 ai 컴퓨터 五子棋 五目並べ 오목게임', related:['tictactoe','minesweeper','g2048'] },
  { key:'csvjoin', h:'csvjoin.html', ic:'🔗', chip:'c-blue',   cat:'데이터', k:'csv 조인 결합 병합 vlookup join merge 키 키열 두 표 합치기 데이터 결합 关联 結合 csv합치기', related:['csvclean','profiler','csvdiff'] },
  { key:'csvdiff', h:'csvdiff.html', ic:'🆚', chip:'c-amber',  cat:'데이터', k:'csv 비교 차이 diff 추가 삭제 변경 감사 검수 버전 비교 데이터 比较 差分 csv비교', related:['csvclean','profiler','csvjoin'] },
  { key:'csvpivot',h:'csvpivot.html', ic:'📊', chip:'c-green',  cat:'데이터', k:'csv 피벗 집계 그룹 합계 평균 개수 pivot group by aggregate 엑셀 피벗테이블 透视 集計 csv집계', related:['profiler','csvclean','csvtable'] },
  { key:'radix',   h:'radix.html',    ic:'🔟', chip:'c-violet', cat:'개발자', k:'진법 변환 2진수 8진수 10진수 16진수 binary hex octal radix base 이진수 16진법 进制 基数 진법변환', related:['hmac','datasize','base64'] },
  { key:'datasize',h:'datasize.html', ic:'💾', chip:'c-cyan',   cat:'변환기', k:'데이터 용량 변환 바이트 byte kb mb gb tb 기가 메가 파일 크기 1024 1000 容量 データ容量 용량변환', related:['unit','radix','pyeong'] },
  { key:'hmac',    h:'hmac.html',     ic:'🔏', chip:'c-rose',   cat:'개발자', k:'hmac sha256 sha1 sha512 메시지 인증 코드 서명 api 웹훅 검증 무결성 hmac생성 签名 署名', related:['hash','crypt','base64'] },
  { key:'coordbatch',h:'coordbatch.html',ic:'🧭', chip:'c-cyan', cat:'GIS', k:'좌표 일괄 변환 여러 좌표 csv 좌표계 경위도 utm-k 중부원점 proj4 batch coordinate 坐标批量 좌표일괄', related:['coord','csvmap','geojsoncsv'] },
  { key:'geojsoncsv',h:'geojsoncsv.html',ic:'🗂️', chip:'c-blue', cat:'GIS', k:'geojson csv 변환 속성 좌표 추출 포인트 위경도 feature 변환 转换 ジオjson csv', related:['geom','coordbatch','csvmap'] },
  { key:'geojsonprec',h:'geojsonprec.html',ic:'📐', chip:'c-violet', cat:'GIS', k:'geojson 좌표 정밀도 소수점 자릿수 용량 줄이기 최적화 simplify precision 优化 精度 지오json경량', related:['geom','geoops','geojsoncsv'] },
  { key:'water', h:'water.html',     ic:'💧', chip:'c-cyan',   cat:'건강', k:'물 섭취량 수분 하루 권장 음수량 다이어트 건강 water intake 喝水 水分 물섭취', related:['calorie','bmi','heartrate'] },
  { key:'bloodpressure',h:'bloodpressure.html',ic:'🩺', chip:'c-rose', cat:'건강', k:'혈압 고혈압 정상 수축기 이완기 분류 대한고혈압학회 단계 blood pressure 血压 血圧 혈압측정', related:['heartrate','bmi','calorie'] },
  { key:'bac',   h:'bac.html',       ic:'🍺', chip:'c-amber',  cat:'건강', k:'음주 혈중알코올농도 bac 위드마크 알코올 술 음주측정 추정 blood alcohol 酒精 飲酒 음주', related:['water','heartrate','calorie'] },
  { key:'roman', h:'roman.html',     ic:'Ⅹ', chip:'c-violet', cat:'변환기', k:'로마 숫자 변환 로마숫자 roman numeral 아라비아 시계 연도 목차 罗马数字 ローマ数字 로마자', related:['radix','numkor','caseconv'] },
  { key:'slug',  h:'slug.html',      ic:'🔡', chip:'c-blue',   cat:'개발자', k:'슬러그 slug url 주소 만들기 퍼머링크 permalink 블로그 게시글 한글 영문 url슬러그 链接 スラッグ', related:['caseconv','urlencode','text'] },
  { key:'csvschema',h:'csvschema.html',ic:'✅', chip:'c-green', cat:'데이터', k:'csv 스키마 검증 규칙 필수 정규식 자료형 고유 검수 품질 validation schema 校验 検証 데이터검증', related:['profiler','csvclean','csvdiff'] },
  { key:'csvviewer',h:'csvviewer.html',ic:'👁️', chip:'c-blue', cat:'데이터', k:'csv 뷰어 보기 필터 검색 열 선택 대용량 페이지 표 viewer filter 查看 ビューア csv보기', related:['profiler','csvclean','csvcols'] },
  { key:'csvcols',h:'csvcols.html',   ic:'🗃️', chip:'c-amber', cat:'데이터', k:'csv 열 편집 선택 순서 재정렬 이름 변경 컬럼 column 정리 编辑 列 csv열', related:['csvclean','csvviewer','csvjoin'] },
  { key:'csvsplit',h:'csvsplit.html', ic:'🪓', chip:'c-rose',  cat:'데이터', k:'csv 분할 샘플링 나누기 무작위 추출 비율 학습 검증 split sample 拆分 抽样 csv분할', related:['csvclean','profiler','csvviewer'] },
  { key:'jsonpath',h:'jsonpath.html', ic:'🧭', chip:'c-violet',cat:'개발자', k:'json 경로 추출 jsonpath 쿼리 와일드카드 값 api 응답 query path 路径 パス json쿼리', related:['json','jsoncsv','regex'] },
  { key:'cron',  h:'cron.html',       ic:'⏰', chip:'c-cyan',   cat:'개발자', k:'cron 크론 크론탭 표현식 스케줄 해석 다음 실행 crontab schedule 定时 クーロン 크론표현식', related:['timestamp','worldclock','radix'] },
  { key:'textstats',h:'textstats.html',ic:'📑', chip:'c-blue', cat:'텍스트', k:'텍스트 통계 문장 단어 문단 읽기 시간 가독성 분석 reading time 文本统计 文章 텍스트분석', related:['char','text','lorem'] },
  { key:'htmlentity',h:'htmlentity.html',ic:'🔣', chip:'c-amber', cat:'개발자', k:'html 엔티티 인코딩 디코딩 특수문자 escape unescape 实体 エンティティ html인코딩', related:['urlencode','base64','caseconv'] },
  { key:'gpa',   h:'gpa.html',        ic:'🎓', chip:'c-green',  cat:'계산기', k:'학점 gpa 평점 평균 대학 성적 4.5 만점 장학금 grade point 绩点 学点 학점계산', related:['percent','salary','date'] },
  { key:'wage',  h:'wage.html',       ic:'⏲️', chip:'c-amber',  cat:'계산기', k:'시급 월급 변환 주휴수당 알바 급여 일급 연봉 최저임금 hourly wage 时薪 時給 시급계산', related:['salary','loan','percent'] },
  { key:'currency',h:'currency.html', ic:'💱', chip:'c-cyan',   cat:'계산기', k:'환율 통화 변환 계산기 달러 엔 유로 외화 수동 환율 exchange rate currency 汇率 為替 환율계산', related:['vat','percent','datasize'] },
  { key:'dday',  h:'dday.html',       ic:'📆', chip:'c-rose',   cat:'시간', k:'디데이 dday d-day 기념일 100일 주년 시험 날짜 카운트 anniversary countdown 纪念日 記念日 디데이계산', related:['date','worldclock','timer'] },
  { key:'stack3d',h:'stack3d.html',ic:'🧱', chip:'c-violet', cat:'게임', k:'3d 타워 쌓기 스택 블록 stack tower 입체 three.js 3D게임 입체게임 쌓기게임', related:['runner3d','maze3d','g2048'] },
  { key:'runner3d',h:'runner3d.html',ic:'🏃', chip:'c-cyan', cat:'게임', k:'3d 러너 엔드리스 달리기 큐브 장애물 피하기 runner 입체 three.js 3D게임 달리기게임', related:['cardodge','stack3d','snake'] },
  { key:'maze3d',h:'maze3d.html',ic:'🌐', chip:'c-green', cat:'게임', k:'3d 미로 찾기 공 굴리기 maze 입체 three.js 미로게임 3D게임 길찾기', related:['stack3d','runner3d','minesweeper'] },
  { key:'chartmaker',h:'chartmaker.html',ic:'📊', chip:'c-violet', cat:'시각화', k:'차트 메이커 그래프 막대 선 원형 파이 산점도 그래프 그리기 chart graph 图表 グラフ 차트생성', related:['stats','regression','palette'] },
  { key:'palette',h:'palette.html',     ic:'🎨', chip:'c-rose',   cat:'시각화', k:'색 팔레트 배색 보색 유사색 삼각 색조합 컬러 스킴 palette color scheme 配色 パレット 색상조합', related:['color','contrast','chartmaker'] },
  { key:'stats', h:'stats.html',        ic:'📈', chip:'c-cyan',   cat:'데이터', k:'통계 평균 중앙값 표준편차 분산 사분위 히스토그램 기술통계 statistics mean stdev 统计 統計 통계계산', related:['regression','profiler','chartmaker'] },
  { key:'regression',h:'regression.html',ic:'📉', chip:'c-green', cat:'데이터', k:'상관 회귀 분석 상관계수 피어슨 선형회귀 추세선 결정계수 r2 correlation regression 回归 相関 회귀분석', related:['stats','chartmaker','profiler'] },
  { key:'jsonschema',h:'jsonschema.html',ic:'🧬', chip:'c-amber', cat:'개발자', k:'json 스키마 생성 추론 json schema draft validation 검증 api 문서 模式 スキーマ 제이슨스키마', related:['json','jsonpath','jsoncsv'] },
  { key:'drawmap',h:'drawmap.html',ic:'✏️', chip:'c-green', cat:'GIS', k:'지도 그리기 도형 점 선 면 폴리곤 wkt geojson 그리기 작도 면적 길이 측정 draw map 绘制 描画 지도작도', related:['geom','coord','geojsoncsv'] },
  { key:'mockdata',h:'mockdata.html',ic:'🎲', chip:'c-amber', cat:'개발자', k:'목업 더미 데이터 생성 가짜 테스트 fake mock data csv json 샘플 시드 假数据 ダミーデータ 테스트데이터', related:['jsonschema','csvviewer','uuid'] },
  { key:'sqlformat',h:'sqlformat.html',ic:'🗄️', chip:'c-blue', cat:'개발자', k:'sql 포매터 포맷 정렬 쿼리 정리 예쁘게 beautify format query 美化 整形 sql정렬', related:['json','jsonschema','jsoncsv'] },
  { key:'mindmap',h:'mindmap.html',ic:'🧠', chip:'c-violet', cat:'시각화', k:'마인드맵 브레인스토밍 생각정리 가지 노드 트리 기획 mind map 思维导图 マインドマップ 마인드맵그리기', related:['diagram','chartmaker','palette'] },
  { key:'imgpalette',h:'imgpalette.html',ic:'🖌️', chip:'c-rose', cat:'시각화', k:'이미지 색상 추출 대표색 주요색 팔레트 컬러 추출 사진 로고 color extract palette 取色 配色 색추출', related:['palette','color','contrast'] },
  { key:'ogimage',h:'ogimage.html',ic:'🖼️', chip:'c-cyan', cat:'시각화', k:'og 이미지 썸네일 생성 sns 공유 카드 소셜 thumbnail 오픈그래프 open graph 缩略图 サムネ 썸네일생성', related:['chartmaker','palette','favicon'] },
  { key:'excel2csv',h:'excel2csv.html',ic:'📊', chip:'c-green', cat:'문서', k:'엑셀 csv json 변환 xlsx xls 시트 추출 convert excel 转换 変換 엑셀변환 엑셀csv', related:['csv2excel','xlsxview','csvviewer'] },
  { key:'csv2excel',h:'csv2excel.html',ic:'📥', chip:'c-blue', cat:'문서', k:'csv json 엑셀 변환 xlsx 만들기 표 to excel 转excel エクセル変換 csv엑셀', related:['excel2csv','xlsxview','jsoncsv'] },
  { key:'xlsxview',h:'xlsxview.html',ic:'📈', chip:'c-cyan', cat:'문서', k:'엑셀 뷰어 보기 미리보기 열기 검색 xlsx viewer 표 시트 查看 ビューア 엑셀열기 엑셀뷰어', related:['excel2csv','csvviewer','csv2excel'] },
  { key:'docx2txt',h:'docx2txt.html',ic:'📝', chip:'c-violet', cat:'문서', k:'워드 docx 텍스트 추출 word 본문 글자 변환 text extract 文档 ワード 워드추출 워드텍스트', related:['pptx2txt','hwpx2txt','wordcount'] },
  { key:'pptx2txt',h:'pptx2txt.html',ic:'📑', chip:'c-amber', cat:'문서', k:'파워포인트 ppt pptx 텍스트 추출 슬라이드 발표 text powerpoint extract 幻灯片 パワポ ppt추출', related:['docx2txt','hwpx2txt','mindmap'] },
  { key:'hwpx2txt',h:'hwpx2txt.html',ic:'📄', chip:'c-rose', cat:'문서', k:'한글 hwpx hwp 텍스트 추출 본문 한컴 hancom 변환 韩文 ハングル 한글추출 한글텍스트', related:['docx2txt','pptx2txt','wordcount'] },
  { key:'pdf2txt',h:'pdf2txt.html',ic:'📕', chip:'c-rose', cat:'문서', k:'pdf 텍스트 추출 글자 본문 변환 text extract 论文 보고서 계약서 pdf추출 pdf텍스트 pdf글자', related:['docx2txt','pdf2img','pmerge'] },
  { key:'pdf2img',h:'pdf2img.html',ic:'🖼️', chip:'c-cyan', cat:'문서', k:'pdf 이미지 변환 png 페이지 캡처 convert image 截图 pdf png pdf이미지 pdf png변환', related:['pdf2txt','img2pdf','psplit'] },
  { key:'mdtable',h:'mdtable.html',ic:'📋', chip:'c-violet', cat:'개발자', k:'마크다운 표 변환 markdown table 깃허브 노션 엑셀 csv 표 markdown 表格 마크다운표 표마크다운', related:['md','csvtable','excel2csv'] },
  { key:'imgwatermark',h:'imgwatermark.html',ic:'💧', chip:'c-blue', cat:'이미지', k:'이미지 워터마크 watermark 도용방지 저작권 반복 대각선 사진 로고 텍스트 水印 透かし 워터마크', related:['image','imgframe','exif'] },
  { key:'imgmerge',h:'imgmerge.html',ic:'🧩', chip:'c-green', cat:'이미지', k:'이미지 합치기 이어붙이기 연결 콜라주 격자 세로 가로 긴 스크린샷 merge combine collage 拼接 結合 이미지합치기', related:['image','imgcrop','imgframe'] },
  { key:'imgframe',h:'imgframe.html',ic:'🎀', chip:'c-violet', cat:'이미지', k:'스크린샷 꾸미기 배경 여백 둥근모서리 그림자 frame mockup beautify screenshot 美化 装飾 스샷꾸미기', related:['image','imgwatermark','ogimage'] },
  { key:'imgmosaic',h:'imgmosaic.html',ic:'🔲', chip:'c-rose', cat:'개인정보', k:'모자이크 블러 가리기 얼굴 개인정보 민감정보 사진 마스킹 mosaic blur pixelate 马赛克 モザイク 모자이크', related:['exif','mask','imgcrop'] },
  { key:'explore3d',h:'explore3d.html',ic:'🌳', chip:'c-green', cat:'게임', k:'3D 탐험 보석 수집 오픈필드 자유이동 어드벤처 3d explore gem adventure roam 探索 探検 3d탐험 자유이동게임', related:['maze3d','topdown','runner3d'] },
  { key:'topdown',h:'topdown.html',ic:'🗺️', chip:'c-amber', cat:'게임', k:'탑다운 탐험 미궁 큰맵 보물찾기 추격 어드벤처 topdown explore treasure 探索 探検 맵탐험 보물찾기게임', related:['explore3d','maze3d','platformer'] },
  { key:'platformer',h:'platformer.html',ic:'🏃', chip:'c-blue', cat:'게임', k:'플랫포머 옆스크롤 점프 달리기 발판 코인 platformer jump run 横版 跳跃 플랫포머 점프게임', related:['runner3d','topdown','explore3d'] },
  { key:'racer3d',h:'racer3d.html',ic:'🏎️', chip:'c-rose', cat:'게임', k:'3d 레이싱 자동차 경주 트랙 서킷 랩타임 주행 racing car race 赛车 レース 3d레이싱 자동차게임', related:['runner3d','space3d','explore3d'] },
  { key:'space3d',h:'space3d.html',ic:'🚀', chip:'c-violet', cat:'게임', k:'3d 우주 비행 우주선 링 소행성 회피 슈팅 space flight ship 太空 宇宙 3d우주 비행게임', related:['racer3d','runner3d','tank'] },
  { key:'tank',h:'tank.html',ic:'🎯', chip:'c-amber', cat:'게임', k:'탱크 전차 배틀 슈팅 아레나 적격파 발사 tank battle shoot 坦克 戦車 탱크게임 전차게임', related:['space3d','topdown','spaceshooter'] },
  { key:'lines',h:'lines.html',ic:'📑', chip:'c-blue', cat:'텍스트', k:'텍스트 줄 정렬 중복제거 빈줄 공백 줄번호 뒤집기 목록 명단 정리 sort unique lines 排序 行 줄정리 중복제거', related:['caseconv','textstats','wordfreq'] },
  { key:'wordfreq',h:'wordfreq.html',ic:'🔠', chip:'c-violet', cat:'텍스트', k:'단어 빈도 분석 카운트 자주쓰는 키워드 글쓰기 seo 통계 word frequency count 词频 単語頻度 단어빈도', related:['textstats','lines','char'] },
  { key:'jsonyaml',h:'jsonyaml.html',ic:'🔄', chip:'c-green', cat:'개발자', k:'json yaml 변환 yml 설정 config convert 转换 変換 json야믈 yaml변환', related:['json','jsoncsv','jsonschema'] },
  { key:'barcode',h:'barcode.html',ic:'▮', chip:'c-amber', cat:'생성기', k:'바코드 생성 code128 ean upc 상품코드 재고 barcode generate 条形码 バーコード 바코드만들기', related:['qr','favicon','base64'] },
  { key:'agecalc',h:'agecalc.html',ic:'🎂', chip:'c-rose', cat:'계산기', k:'만나이 계산 나이 연나이 세는나이 띠 별자리 생일 age 年龄 年齢 만나이계산기 나이계산', related:['dday','lunar','workdays'] },
  { key:'dutchpay',h:'dutchpay.html',ic:'🧮', chip:'c-blue', cat:'계산기', k:'더치페이 n빵 엔빵 나누기 1인당 회식 정산 split bill 摊分 割り勘 더치페이 정산', related:['percent','vat','salary'] },
  { key:'discount',h:'discount.html',ic:'🏷️', chip:'c-amber', cat:'계산기', k:'할인 계산 할인율 세일 정가 할인가 쿠폰 쇼핑 discount sale 折扣 割引 할인계산기 세일계산', related:['percent','vat','currency'] },
  { key:'savings',h:'savings.html',ic:'🐷', chip:'c-green', cat:'계산기', k:'적금 예금 이자 계산 만기 단리 복리 이자소득세 저축 savings deposit interest 存款 利息 적금계산기 예금이자', related:['loan','salary','vat'] },
  { key:'mbti',h:'mbti.html',ic:'🧩', chip:'c-violet', cat:'심리·운세', k:'mbti 성격 유형 검사 테스트 16personalities 심리 personality test 性格 性格診断 엠비티아이 성격검사', related:['bloodtype','biorhythm','namematch'] },
  { key:'bloodtype',h:'bloodtype.html',ic:'🩸', chip:'c-rose', cat:'심리·운세', k:'혈액형 성격 abo a형 b형 o형 ab형 궁합 재미 blood type 血型 血液型 혈액형성격', related:['mbti','namematch','biorhythm'] },
  { key:'biorhythm',h:'biorhythm.html',ic:'📈', chip:'c-green', cat:'심리·운세', k:'바이오리듬 신체 감성 지성 컨디션 곡선 리듬 biorhythm 生物节律 バイオリズム 바이오리듬', related:['mbti','agecalc','bloodtype'] },
  { key:'namematch',h:'namematch.html',ic:'💕', chip:'c-amber', cat:'심리·운세', k:'이름 궁합 테스트 사랑 연애 커플 재미 획수 name compatibility 姓名配对 相性 이름궁합', related:['bloodtype','mbti','agecalc'] },
  { key:'saju',h:'saju.html',ic:'🔮', chip:'c-cyan', cat:'심리·운세', k:'사주 만세력 사주팔자 팔자 천간지지 간지 오행 띠 일간 명리 saju four pillars 四柱 八字 사주팔자 만세력', related:['agecalc','lunar','bloodtype'] },
  { key:'copsrobbers',h:'copsrobbers.html',ic:'🚔', chip:'c-blue', cat:'게임', k:'경찰과 도둑 2인용 추격 보석 도둑잡기 멀티 둘이서 cops robbers chase 2player 警察小偷 泥棒 경찰도둑 2인용게임', related:['tank','topdown','maze'] },
  { key:'slimefps',h:'slimefps.html',ic:'🔫', chip:'c-green', cat:'게임', k:'fps 슈팅 1인칭 총 슬라임 건앤슬라임 gun slime shooter 3d 사격 射击 シューティング 슬라임슈팅 fps게임', related:['space3d','tank','spaceshooter'] },
  { key:'typing',h:'typing.html',ic:'⌨️', chip:'c-blue', cat:'텍스트', k:'타자 속도 측정 타이핑 연습 타수 cpm wpm 정확도 typing speed test 打字 タイピング 타자연습 타자속도', related:['lines','wordfreq','textstats'] },
  { key:'roulette',h:'roulette.html',ic:'🎯', chip:'c-rose', cat:'생성기', k:'돌림판 룰렛 추첨 랜덤 뽑기 제비 메뉴 결정 roulette wheel spinner picker 转盘 ルーレット 돌림판 추첨기', related:['ladder','lotto','pw'] },
  { key:'emoji',h:'emoji.html',ic:'😀', chip:'c-amber', cat:'텍스트', k:'이모지 이모티콘 emoji 특수문자 기호 복사 검색 emoticon symbol 表情符号 絵文字 이모지모음', related:['htmlentity','caseconv','lines'] },
  { key:'xmlformat',h:'xmlformat.html',ic:'📐', chip:'c-green', cat:'개발자', k:'xml 포매터 정렬 압축 검증 포맷 rss svg beautify minify format 格式化 整形 xml정렬', related:['jsonyaml','json','sqlformat'] },
  { key:'cyberchef',h:'cyberchef.html',ic:'🔪', chip:'c-violet', cat:'개발자', k:'사이버셰프 cyberchef 암복호화 인코딩 디코딩 base64 hex 해시 jwt aes 정규식 변환 데이터 보안 cyber chef encode decode 加密 暗号 사이버셰프', related:['base64','hash','jwt'] },
  { key:'excalidraw',h:'excalidraw.html',ic:'✏️', chip:'c-cyan', cat:'시각화', k:'엑스칼리드로 excalidraw 화이트보드 다이어그램 손그림 와이어프레임 아키텍처 플로차트 그림 whiteboard draw 白板 ホワイトボード 엑스칼리드로', related:['diagram','mindmap','drawmap'] },
  { key:'morse',h:'morse.html',ic:'📻', chip:'c-blue', cat:'텍스트', k:'모스부호 모스 변환 점선 신호 소리 morse code 摩尔斯 モールス 모스부호변환', related:['fancytext','base64','emoji'] },
  { key:'fancytext',h:'fancytext.html',ic:'🔡', chip:'c-violet', cat:'텍스트', k:'꾸미기 글씨 특수문자 폰트 sns 인스타 닉네임 유니코드 fancy text font 花体字 装飾文字 특수글씨', related:['emoji','textflip','caseconv'] },
  { key:'hangul',h:'hangul.html',ic:'한', chip:'c-rose', cat:'텍스트', k:'한글 자모 분해 초성 추출 중성 종성 타수 결합 hangul jamo decompose 韩文 ハングル 초성추출', related:['typing','lines','char'] },
  { key:'textflip',h:'textflip.html',ic:'🙃', chip:'c-amber', cat:'텍스트', k:'텍스트 뒤집기 거꾸로 역순 상하반전 미러 flip reverse upside down 翻转 反転 거꾸로글씨', related:['fancytext','emoji','caseconv'] },
  { key:'numformat',h:'numformat.html',ic:'🔢', chip:'c-green', cat:'변환기', k:'숫자 포맷 천단위 콤마 만 억 조 단위 통화 반올림 number format 数字格式 数値 천단위콤마', related:['numkor','num2en','radix'] },
  { key:'num2en',h:'num2en.html',ic:'🔤', chip:'c-cyan', cat:'변환기', k:'숫자 영어 변환 금액 영문 표기 number to words english 数字英文 英語 숫자영어', related:['numkor','numformat','roman'] },
  { key:'unicodeconv',h:'unicodeconv.html',ic:'🆎', chip:'c-violet', cat:'개발자', k:'유니코드 변환 코드포인트 이스케이프 utf-8 바이트 unicode escape codepoint 编码 文字コード 유니코드변환', related:['htmlentity','base64','unicodeconv'] },
  { key:'dice',h:'dice.html',ic:'🎲', chip:'c-amber', cat:'생성기', k:'주사위 랜덤 숫자 굴리기 보드게임 추첨 무작위 dice random roll 骰子 サイコロ 주사위', related:['roulette','lotto','ladder'] },
  { key:'severance',h:'severance.html',ic:'💼', chip:'c-green', cat:'계산기', k:'퇴직금 계산 평균임금 재직일수 퇴사 severance pay 退职金 退職金 퇴직금계산기', related:['salary','loan','savings'] },
  { key:'jeonse',h:'jeonse.html',ic:'🏠', chip:'c-blue', cat:'계산기', k:'전월세 전환 전세 월세 보증금 전환율 jeonse rent 房租 家賃 전월세전환 전세월세', related:['loan','vat','savings'] },
  { key:'fuelcost',h:'fuelcost.html',ic:'⛽', chip:'c-amber', cat:'계산기', k:'유류비 기름값 연비 주유 카풀 거리 fuel cost 油费 ガソリン代 유류비계산 기름값', related:['fuelcost','currency','percent'] },
  { key:'timecalc',h:'timecalc.html',ic:'⏱️', chip:'c-cyan', cat:'계산기', k:'시간 계산 더하기 빼기 차이 시분초 근무시간 time calculator 时间计算 時間計算 시간계산기', related:['workdays','dday','timecalc'] },
  { key:'duedate',h:'duedate.html',ic:'🤰', chip:'c-rose', cat:'건강', k:'출산 예정일 임신 주수 분기 lmp 임신계산 due date pregnancy 预产期 出産予定日 출산예정일', related:['agecalc','dday','bmi'] },
  { key:'electricity',h:'electricity.html',ic:'⚡', chip:'c-amber', cat:'계산기', k:'전기요금 누진제 kwh 한전 전기세 electricity bill 电费 電気料金 전기요금계산기', related:['vat','percent','savings'] },
  { key:'idealweight',h:'idealweight.html',ic:'⚖️', chip:'c-green', cat:'건강', k:'표준체중 적정체중 정상체중 bmi broca devine ideal weight 标准体重 標準体重 표준체중계산', related:['bmi','calorie','water'] },
  { key:'sizeconv',h:'sizeconv.html',ic:'👟', chip:'c-violet', cat:'변환기', k:'사이즈 변환 신발 의류 옷 mm us eu uk 해외직구 size chart 尺码 サイズ 사이즈변환표', related:['unit','pyeong','numformat'] },
  { key:'csv2sql',h:'csv2sql.html',ic:'🗃️', chip:'c-blue', cat:'개발자', k:'csv sql insert 변환 db 적재 데이터베이스 쿼리 생성 csv to sql 转换 변환', related:['sqlformat','jsoncsv','csvviewer'] },
  { key:'json2ts',h:'json2ts.html',ic:'🔷', chip:'c-cyan', cat:'개발자', k:'json typescript 인터페이스 타입 변환 ts interface type 类型 型 타입생성', related:['jsonschema','json','jsonyaml'] },
  { key:'jsondiff',h:'jsondiff.html',ic:'🔍', chip:'c-amber', cat:'개발자', k:'json 비교 diff 차이 변경 추가 삭제 compare 比较 比較 json비교', related:['diff','csvdiff','jsonpath'] },
  { key:'ulid',h:'ulid.html',ic:'🆔', chip:'c-violet', cat:'개발자', k:'ulid 고유 아이디 정렬 식별자 uuid 대안 생성 sortable id 唯一标识 識別子', related:['uuid','hash','hmac'] },
  { key:'envjson',h:'envjson.html',ic:'🔧', chip:'c-green', cat:'개발자', k:'env json 변환 환경변수 dotenv 설정 config 环境变量 環境変数 env변환', related:['jsonyaml','json','xmlformat'] },
  { key:'passphrase',h:'passphrase.html',ic:'🔐', chip:'c-rose', cat:'생성기', k:'패스프레이즈 비밀번호 단어 조합 외우기쉬운 암호 passphrase password 密码 パスフレーズ 패스프레이즈', related:['pw','pwcheck','dice'] },
  { key:'pwcheck',h:'pwcheck.html',ic:'🛡️', chip:'c-blue', cat:'개인정보', k:'비밀번호 강도 측정 엔트로피 해킹시간 안전성 password strength 密码强度 強度 비밀번호강도', related:['pw','passphrase','hash'] },
  { key:'colorname',h:'colorname.html',ic:'🎨', chip:'c-amber', cat:'시각화', k:'색 이름 변환 css color name hex rgb 색상명 가까운색 color name 颜色名 色名 색이름', related:['color','palette','gradient'] },
  { key:'rps',h:'rps.html',ic:'✊', chip:'c-blue', cat:'게임', k:'가위바위보 묵찌빠 컴퓨터 대결 rps rock paper scissors 石头剪刀布 じゃんけん 가위바위보', related:['dice','roulette','reaction'] },
  { key:'reaction',h:'reaction.html',ic:'⚡', chip:'c-amber', cat:'게임', k:'반응속도 순발력 테스트 클릭 ms reaction time 反应速度 反応速度 반응속도테스트', related:['simon','whack','typing'] },
  { key:'baseball',h:'baseball.html',ic:'⚾', chip:'c-green', cat:'게임', k:'숫자야구 스트라이크 볼 추리 number baseball 数字棒球 数当て 숫자야구게임', related:['gomoku','minesweeper','baseball'] },
  { key:'puzzle15',h:'puzzle15.html',ic:'🔢', chip:'c-violet', cat:'게임', k:'15퍼즐 슬라이드 숫자 퍼즐 8퍼즐 sliding puzzle 数字华容道 スライドパズル 15퍼즐', related:['g2048','memorygame','minesweeper'] },
  { key:'simon',h:'simon.html',ic:'🎵', chip:'c-rose', cat:'게임', k:'사이먼 색 소리 순서 기억 메모리 simon says memory 记忆 サイモン 사이먼게임', related:['memorygame','reaction','whack'] },
  { key:'clicker',h:'clicker.html',ic:'🪙', chip:'c-amber', cat:'게임', k:'클리커 방치형 키우기 코인 클릭 idle clicker 放置 クリッカー 클리커게임', related:['g2048','whack','clicker'] },
  { key:'tetris',h:'tetris.html',ic:'🧱', chip:'c-cyan', cat:'게임', k:'테트리스 블록 쌓기 줄없애기 tetris block 俄罗斯方块 テトリス 테트리스게임', related:['g2048','breakout','snake'] },
  { key:'flappy',h:'flappy.html',ic:'🐤', chip:'c-blue', cat:'게임', k:'플래피 버드 점프 파이프 한손 flappy bird tap 飞翔 フラッピー 플래피버드', related:['runner3d','cardodge','breakout'] },
  { key:'tarot',h:'tarot.html',ic:'🔮', chip:'c-violet', cat:'심리·운세', k:'타로 카드 한장 뽑기 운세 메이저아르카나 tarot card 塔罗 タロット 타로카드', related:['saju','fortunecookie','mbti'] },
  { key:'fortunecookie',h:'fortunecookie.html',ic:'🥠', chip:'c-amber', cat:'심리·운세', k:'포춘쿠키 오늘의 한마디 행운 메시지 운세 fortune cookie 幸运饼 おみくじ 포춘쿠키', related:['tarot','saju','lotto'] },
  { key:'zodiacanim',h:'zodiacanim.html',ic:'🐯', chip:'c-rose', cat:'심리·운세', k:'띠별 성격 십이지 띠 운세 궁합 zodiac animal 生肖 干支 띠성격 띠별운세', related:['saju','bloodtype','agecalc'] },
  { key:'img2ascii',h:'img2ascii.html',ic:'🔤', chip:'c-green', cat:'이미지', k:'이미지 아스키 아트 ascii art 글자 그림 변환 사진 image to ascii 字符画 アスキーアート 아스키아트', related:['pixelate','imgfilter','imgpalette'] },
  { key:'pixelate',h:'pixelate.html',ic:'🟦', chip:'c-cyan', cat:'이미지', k:'이미지 픽셀화 도트화 픽셀아트 모자이크 pixelate dot art 像素化 ピクセル化 픽셀아트', related:['imgmosaic','imgfilter','img2ascii'] },
  { key:'imgfilter',h:'imgfilter.html',ic:'🎞️', chip:'c-violet', cat:'이미지', k:'이미지 필터 흑백 세피아 밝기 대비 채도 블러 image filter grayscale 滤镜 フィルター 이미지필터', related:['image','imgcrop','imgframe'] },
  { key:'qrdecode',h:'qrdecode.html',ic:'📷', chip:'c-blue', cat:'이미지', k:'qr 읽기 디코더 인식 스캔 코드 qr decoder reader scan 二维码识别 QR読み取り qr읽기', related:['qr','barcode','exif'] },
  { key:'angle',h:'angle.html',ic:'📐', chip:'c-amber', cat:'변환기', k:'각도 변환 도 라디안 그라드 회전수 도분초 dms angle radian 角度 角度変換 각도변환', related:['unit','radix','numformat'] },
  { key:'romanize',h:'romanize.html',ic:'🔡', chip:'c-blue', cat:'텍스트', k:'한글 로마자 변환 영문 표기 이름 주소 romanize korean 罗马字 ローマ字 로마자변환', related:['hangul','caseconv','slug'] },
  { key:'nickname',h:'nickname.html',ic:'🐣', chip:'c-rose', cat:'생성기', k:'닉네임 생성 별명 랜덤 아이디 게임 sns nickname generator 昵称 ニックネーム 닉네임생성기', related:['passphrase','dice','roulette'] },
  { key:'placeholder',h:'placeholder.html',ic:'🖼️', chip:'c-violet', cat:'생성기', k:'플레이스홀더 더미 이미지 목업 자리표시 placeholder dummy image 占位图 ダミー画像 더미이미지', related:['ogimage','favicon','imgframe'] },
  { key:'steps',h:'steps.html',ic:'🚶', chip:'c-green', cat:'건강', k:'걸음 수 거리 칼로리 만보 보폭 소모 steps calories distance 步数 歩数 걸음수칼로리', related:['calorie','pace','water'] },
  { key:'pace',h:'pace.html',ic:'🏃', chip:'c-amber', cat:'건강', k:'러닝 페이스 마라톤 기록 속도 달리기 분km running pace 配速 ペース 러닝페이스', related:['steps','calorie','heartrate'] },
  { key:'cooking',h:'cooking.html',ic:'🥄', chip:'c-cyan', cat:'변환기', k:'요리 계량 변환 컵 큰술 작은술 ml g 레시피 cooking measure cup tbsp 量勺 計量 요리계량', related:['unit','numformat','sizeconv'] },
];
